### PR TITLE
Adds a training section for courses.

### PR DESCRIPTION
**Pull request by rob-smallshire**
Includes a link to a training course by Sixty North.  Disclosure: I part own and work for Sixty North.

### CODE REVIEW

**Comment by valentjedi** [comment]
Hi, that's cool. Does one should physically present in classroom or it'll be some kind of webinar? Will it be one-time classroom or some kind of periodic event? Will there be some video content out of it and will it be paid/free? I mostly ask because I'm interested myself :)

**Comment by rob-smallshire** [comment]
You and your laptop need to be physically present. We run this course worldwide. I guess we need at least four people to make the course worthwhile for a private course.  We might also consider running a public course where individuals can sign up, if there's sufficient demand.

**Comment by valentjedi** [comment]
`If you'd like us to show up at your local PyCon let us (and them!) know.` Unfortunately I live in the ass of the world so no PyCon here. I'll add this course to the list since someone might be interested as I am and your original talk about DDD in Python was main inspiring point for this list :) I'll also add a little notice that course is paid. Thanks for PR!

**Comment by rob-smallshire** [comment]
You should organise one, however small.  We've been to PyCon Belarus, and that was small.  I've *always* wanted to travel the trans-siberian railway, so if you organise a small PyCon Khabarovsk we'll come and do our workshop, for free.

**Pull request merged**
